name: Build ZenithSkyPvP

on:
  push:
  workflow_dispatch:

jobs:
  build:
    name: Build ZenithSkyPvP
    runs-on: ubuntu-latest

    steps:

      - name: Checkout source
        uses: actions/checkout@v4

      - name: Check Java
        run: |
          java -version
          mvn -version

      - name: Build with Maven
        run: |
          mvn -B clean package -DskipTests

      - name: Show build files
        run: |
          echo "===== TARGET ====="
          ls -lah target || true

      - name: Upload JAR
        uses: actions/upload-artifact@v4
        with:
          name: ZenithSkyPvP-2.2.0
          path: target/ZenithSkyPvP-2.2.0.jar
          if-no-files-found: error